-- Initial schema. Compatible with PostgreSQL and H2 in PostgreSQL mode.
-- Domain model inspired by "enclave" learning app: categories -> levels (CEFR)
-- -> blocks -> exercises -> questions. Gamification: XP, stars, streak,
-- daily goal, word of the day.

CREATE TABLE categories (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         VARCHAR(32)  NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    tagline      VARCHAR(180),
    description  VARCHAR(500),
    position     INT          NOT NULL DEFAULT 0
);

CREATE TABLE levels (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id       BIGINT       NOT NULL REFERENCES categories(id),
    code              VARCHAR(8)   NOT NULL,
    position          INT          NOT NULL,
    display_name      VARCHAR(120) NOT NULL,
    headline          VARCHAR(180),
    description       VARCHAR(500),
    estimated_hours   INT          NOT NULL DEFAULT 0,
    total_exercises   INT          NOT NULL DEFAULT 0,
    locked            BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_levels_category_code UNIQUE (category_id, code)
);
CREATE INDEX idx_levels_category_id ON levels (category_id);

CREATE TABLE blocks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id      BIGINT       NOT NULL REFERENCES levels(id) ON DELETE CASCADE,
    position      INT          NOT NULL,
    title         VARCHAR(120) NOT NULL,
    subtitle      VARCHAR(180),
    start_exercise INT         NOT NULL,
    end_exercise   INT         NOT NULL,
    CONSTRAINT uk_blocks_level_position UNIQUE (level_id, position)
);
CREATE INDEX idx_blocks_level_id ON blocks (level_id);

CREATE TABLE exercises (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id          BIGINT       NOT NULL REFERENCES levels(id) ON DELETE CASCADE,
    block_id          BIGINT       NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
    position          INT          NOT NULL,
    title             VARCHAR(120) NOT NULL,
    topic             VARCHAR(120),
    questions_count   INT          NOT NULL DEFAULT 0,
    estimated_minutes INT          NOT NULL DEFAULT 6,
    xp_reward         INT          NOT NULL DEFAULT 50,
    locked            BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_exercises_level_position UNIQUE (level_id, position)
);
CREATE INDEX idx_exercises_level_id ON exercises (level_id);
CREATE INDEX idx_exercises_block_id ON exercises (block_id);

CREATE TABLE questions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_id      BIGINT       NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    position         INT          NOT NULL,
    type             VARCHAR(40)  NOT NULL,
    prompt           VARCHAR(500) NOT NULL,
    prompt_highlight VARCHAR(120),
    context          VARCHAR(255),
    hint             VARCHAR(255),
    correct_answer   VARCHAR(255) NOT NULL,
    explanation      VARCHAR(800),
    CONSTRAINT uk_questions_exercise_position UNIQUE (exercise_id, position)
);
CREATE INDEX idx_questions_exercise_id ON questions (exercise_id);

CREATE TABLE question_options (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id   BIGINT       NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    position      INT          NOT NULL,
    label         VARCHAR(255) NOT NULL,
    option_value  VARCHAR(255) NOT NULL,
    is_correct    BOOLEAN      NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_question_options_question_id ON question_options (question_id);

CREATE TABLE words_of_day (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    on_date         DATE         NOT NULL UNIQUE,
    word            VARCHAR(80)  NOT NULL,
    phonetic        VARCHAR(80),
    part_of_speech  VARCHAR(40),
    definition_es   VARCHAR(255) NOT NULL,
    example_en      VARCHAR(255),
    example_es      VARCHAR(255)
);

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(180) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    role          VARCHAR(32)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL
);

CREATE TABLE user_streaks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    current_streak    INT       NOT NULL DEFAULT 0,
    longest_streak    INT       NOT NULL DEFAULT 0,
    total_xp          INT       NOT NULL DEFAULT 0,
    last_active_date  DATE
);

CREATE TABLE user_daily_stats (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    on_date               DATE      NOT NULL,
    xp_earned             INT       NOT NULL DEFAULT 0,
    minutes_practiced     INT       NOT NULL DEFAULT 0,
    exercises_completed   INT       NOT NULL DEFAULT 0,
    daily_goal_minutes    INT       NOT NULL DEFAULT 10,
    daily_goal_xp         INT       NOT NULL DEFAULT 100,
    CONSTRAINT uk_user_daily_stats_user_date UNIQUE (user_id, on_date)
);
CREATE INDEX idx_user_daily_stats_user_id ON user_daily_stats (user_id);

CREATE TABLE user_exercise_progress (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    exercise_id       BIGINT    NOT NULL REFERENCES exercises(id) ON DELETE CASCADE,
    status            VARCHAR(32) NOT NULL DEFAULT 'AVAILABLE',
    stars             INT       NOT NULL DEFAULT 0,
    correct_answers   INT       NOT NULL DEFAULT 0,
    total_answers     INT       NOT NULL DEFAULT 0,
    questions_done    INT       NOT NULL DEFAULT 0,
    xp_earned         INT       NOT NULL DEFAULT 0,
    last_seen_at      TIMESTAMP NOT NULL,
    completed_at      TIMESTAMP,
    CONSTRAINT uk_user_exercise_progress UNIQUE (user_id, exercise_id)
);
CREATE INDEX idx_user_exercise_progress_user_id ON user_exercise_progress (user_id);

CREATE TABLE user_question_attempts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT    NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    question_id       BIGINT    NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
    attempts          INT       NOT NULL DEFAULT 0,
    correct           BOOLEAN   NOT NULL DEFAULT FALSE,
    hints_used        INT       NOT NULL DEFAULT 0,
    last_seen_at      TIMESTAMP NOT NULL,
    CONSTRAINT uk_user_question_attempts UNIQUE (user_id, question_id)
);
CREATE INDEX idx_user_question_attempts_user_id ON user_question_attempts (user_id);
