-- Diccionario de términos por categoría/nivel.
-- Se consulta desde /v1/dictionary con búsqueda case-insensitive y filtros
-- por category_type (GENERAL/TECH) y level_code (A1..C2).

CREATE TABLE dictionary_entries (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word            VARCHAR(80)  NOT NULL,
    phonetic        VARCHAR(80),
    part_of_speech  VARCHAR(40),
    definition_es   VARCHAR(255) NOT NULL,
    example_en      VARCHAR(255),
    example_es      VARCHAR(255),
    category_type   VARCHAR(32)  NOT NULL,
    level_code      VARCHAR(8)   NOT NULL,
    CONSTRAINT uk_dictionary_word_cat UNIQUE (word, category_type)
);

CREATE INDEX idx_dictionary_word        ON dictionary_entries (word);
CREATE INDEX idx_dictionary_cat_level   ON dictionary_entries (category_type, level_code);
