ALTER TABLE users
    ADD COLUMN IF NOT EXISTS bio TEXT,
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(512),
    ADD COLUMN IF NOT EXISTS daily_goal_minutes INT DEFAULT 15 NOT NULL,
    ADD COLUMN IF NOT EXISTS daily_goal_xp INT DEFAULT 50 NOT NULL,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
